//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensiblePOS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensiblePOS.Resources.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        internal static string ALL_CATEGORY {
            get {
                return ResourceManager.GetString("ALL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการลบรายการสั่งซื้อทั้งหมด?.
        /// </summary>
        internal static string DIALOG_MSG_CLEAR_ORDERS {
            get {
                return ResourceManager.GetString("DIALOG_MSG_CLEAR_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลสินค้า.
        /// </summary>
        internal static string DIALOG_MSG_PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIALOG_MSG_PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณยังไม่สามารถเข้าใช้งานจุดขายนี้ได้เนื่องจากยังไม่ได้รับอนุญาติ
        ///กรุณาติดต่อเจ้าหน้าที่ที่เกี่ยวข้องเพื่อเปืดสิทธิ์.
        /// </summary>
        internal static string DIALOG_MSG_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("DIALOG_MSG_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถใช้งานได้.
        /// </summary>
        internal static string DIALOG_TITLE_AUTHORIZE {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบรายการสั่งซื้อ.
        /// </summary>
        internal static string DIALOG_TITLE_CLEAR_ORDERS {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_CLEAR_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การค้นหาสินค้า.
        /// </summary>
        internal static string DIALOG_TITLE_SEARCH_PRODUCT {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_SEARCH_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด.
        /// </summary>
        internal static string DISCOUNT_TYPE {
            get {
                return ResourceManager.GetString("DISCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด: {0}.
        /// </summary>
        internal static string ITEM_DISCOUNT_TITLE {
            get {
                return ResourceManager.GetString("ITEM_DISCOUNT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนวน.
        /// </summary>
        internal static string LABEL_CALCULATE {
            get {
                return ResourceManager.GetString("LABEL_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงิน.
        /// </summary>
        internal static string LABEL_PAY {
            get {
                return ResourceManager.GetString("LABEL_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบเสร็จล่าสุด: {0}.
        /// </summary>
        internal static string LABEL_PREVIOUS_RECEIPT {
            get {
                return ResourceManager.GetString("LABEL_PREVIOUS_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมทั้งหมด {0} ชิ้น.
        /// </summary>
        internal static string LABEL_TOTAL_PRODUCTS {
            get {
                return ResourceManager.GetString("LABEL_TOTAL_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินสด.
        /// </summary>
        internal static string PAY_METHOD_CASH {
            get {
                return ResourceManager.GetString("PAY_METHOD_CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัตรเครดิต.
        /// </summary>
        internal static string PAY_METHOD_CREDIT_CARD {
            get {
                return ResourceManager.GetString("PAY_METHOD_CREDIT_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พร้อมเพย์.
        /// </summary>
        internal static string PAY_METHOD_PROMPTPAY {
            get {
                return ResourceManager.GetString("PAY_METHOD_PROMPTPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า.
        /// </summary>
        internal static string PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดที่ไม่สามารถแบ่งคำนวน % ได้ (เกิน {0} ชิ้น).
        /// </summary>
        internal static string REMARK_DISCOUNT_TYPE_1 {
            get {
                return ResourceManager.GetString("REMARK_DISCOUNT_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดที่ไม่สามารถแบ่งคำนวน % ได้.
        /// </summary>
        internal static string REMARK_DISCOUNT_TYPE_2 {
            get {
                return ResourceManager.GetString("REMARK_DISCOUNT_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดที่ไม่สามารถแบ่งคำนวนได้ (เกินจำนวนที่กำหนด).
        /// </summary>
        internal static string REMARK_DISCOUNT_TYPE_3 {
            get {
                return ResourceManager.GetString("REMARK_DISCOUNT_TYPE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดที่ไม่สามารถแบ่งได้.
        /// </summary>
        internal static string REMARK_DISCOUNT_TYPE_4 {
            get {
                return ResourceManager.GetString("REMARK_DISCOUNT_TYPE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string UNIT_NAME {
            get {
                return ResourceManager.GetString("UNIT_NAME", resourceCulture);
            }
        }
    }
}
