//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensiblePOS.Backoffice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensiblePOS.Backoffice.Resources.ReportForm", typeof(ReportForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        internal static string ALL_ITEM {
            get {
                return ResourceManager.GetString("ALL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกเสร็จสิ้น.
        /// </summary>
        internal static string DIALOG_MSG_EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("DIALOG_MSG_EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การบันทึกเป็น CSV.
        /// </summary>
        internal static string DIALOG_TITLE_EXPORT_CSV {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_EXPORT_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า (sku:xxx) หรือ กลุ่มสินค้า (cat:xxx).
        /// </summary>
        internal static string KEYWORD_PLACEHOLDER_CURRENT_STOCK {
            get {
                return ResourceManager.GetString("KEYWORD_PLACEHOLDER_CURRENT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า (sku:xxx).
        /// </summary>
        internal static string KEYWORD_PLACEHOLDER_ITEM_SOLD {
            get {
                return ResourceManager.GetString("KEYWORD_PLACEHOLDER_ITEM_SOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขใบเสร็จ (inv:xxx).
        /// </summary>
        internal static string KEYWORD_PLACEHOLDER_RECEIPT {
            get {
                return ResourceManager.GetString("KEYWORD_PLACEHOLDER_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขใบเสร็จ (inv:xxx) หรือ รหัสสินค้า (sku:xxx).
        /// </summary>
        internal static string KEYWORD_PLACEHOLDER_RECEIPT_DETAIL {
            get {
                return ResourceManager.GetString("KEYWORD_PLACEHOLDER_RECEIPT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. สต๊อก.
        /// </summary>
        internal static string REPORT_CURRENT_STOCK_TITLE {
            get {
                return ResourceManager.GetString("REPORT_CURRENT_STOCK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. รายได้ต่อวัน.
        /// </summary>
        internal static string REPORT_DAILY_PROFIT_TITLE {
            get {
                return ResourceManager.GetString("REPORT_DAILY_PROFIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. ยอดขายสินค้า.
        /// </summary>
        internal static string REPORT_ITEM_SOLD_TITLE {
            get {
                return ResourceManager.GetString("REPORT_ITEM_SOLD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. รายละเอียดการขาย.
        /// </summary>
        internal static string REPORT_RECEIPT_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("REPORT_RECEIPT_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. รายการใบเสร็จ.
        /// </summary>
        internal static string REPORT_RECEIPT_TITLE {
            get {
                return ResourceManager.GetString("REPORT_RECEIPT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. ผลงานพนักงานขาย.
        /// </summary>
        internal static string REPORT_SALE_PERFORMANCE_TITLE {
            get {
                return ResourceManager.GetString("REPORT_SALE_PERFORMANCE_TITLE", resourceCulture);
            }
        }
    }
}
